title: Shanglan Gao's Academic Homepage
page-top-title: Shanglan Gao's Academic Homepage
top-section-bg-text: Stay curious, keep learning.
home-subtitle: Shanglan Gao&ensp;|&ensp;Geely Auto Group
copyright-text: "&copy; Shanglan Gao 2023-2025. All Rights Reserved."
